'use strict';function y(h,a,b,d){h.A.dc(h.Qa,a,b,d,void 0)}function C(h,a,b,d){h.A.oa?y(h,a,b,d):h.A.Ze()._OnMessageFromDOM({type:"event",component:h.Qa,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function D(h,a,b){h.A.B(h.Qa,a,b)}function E(h,a){for(const [b,d]of a)D(h,b,d)}function F(h){h.Ib||(h.A.Ke(h.Rd),h.Ib=!0)}window.kb=class{constructor(h,a){this.A=h;this.Qa=a;this.Ib=!1;this.Rd=()=>this.ya()}Wc(){}ya(){}};function H(h){-1!==h.Ja&&(self.clearTimeout(h.Ja),h.Ja=-1)}
window.Be=class{constructor(h,a){this.Bc=h;this.ng=a;this.Ja=-1;this.Jb=-Infinity;this.Sd=()=>{this.Ja=-1;this.Jb=Date.now();this.Va=!0;this.Bc();this.Va=!1};this.Bd=this.Va=!1}c(){H(this);this.Sd=this.Bc=null}};"use strict";function I(h,a){D(h,"get-element",b=>{const d=h.ca.get(b.elementId);return a(d,b)})}
window.Gg=class extends self.kb{constructor(h,a){super(h,a);this.ca=new Map;this.Ac=!0;E(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ca.get(b);this.Ac&&d.parentElement.removeChild(d);this.ca.delete(b)}}],["set-visible",b=>{this.Ac&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Ac){var d=this.ca.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>{{const d=this.ca.get(b.elementId);b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);I(this,b=>b)}};"use strict";
{const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function a(u){if(u.xg){const f=document.createElement("script");f.async=!1;f.textContent=u.Ag;document.head.appendChild(f)}else return new Promise((f,l)=>{const c=document.createElement("script");c.onload=f;c.onerror=l;c.async=!1;c.src=u;document.head.appendChild(c)})}let b=new Audio;const d={"audio/webm; codecs=opus":!!b.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!b.canPlayType("audio/ogg; codecs=opus"),
"audio/webm; codecs=vorbis":!!b.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!b.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!b.canPlayType("audio/mp4"),"audio/mpeg":!!b.canPlayType("audio/mpeg")};b=null;async function g(u){u=await n(u);return(new TextDecoder("utf-8")).decode(u)}function n(u){return new Promise((f,l)=>{const c=new FileReader;c.onload=e=>f(e.target.result);c.onerror=e=>l(e);c.readAsArrayBuffer(u)})}const q=[];let t=0;window.RealFile=window.File;const w=
[],A=new Map,v=new Map;let x=0;const B=[];self.Lg=function(u){if("function"!==typeof u)throw Error("runOnStartup called without a function");B.push(u)};const z=new Set(["cordova","playable-ad","instant-games"]);window.qb=class u{constructor(f){this.oa=f.Cg;this.ma=null;this.V="";this.Qc=f.zg;this.jb={};this.Ca=this.ib=null;this.Gb=[];this.Xa=this.I=this.Ha=null;this.Ga=-1;this.sg=()=>this.yf();this.Fa=[];this.W=f.Td;!this.oa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||(this.oa=
!1);z.has(this.W)&&this.oa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.oa=!1);this.Tc=!1;this.Lb=this.ha=null;"html5"!==this.W&&"playable-ad"!==this.W||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",
l=>this.gf(l));this.B("runtime","create-job-worker",()=>this.hf());"cordova"===this.W?document.addEventListener("deviceready",()=>this.pd(f)):this.pd(f)}c(){this.kc();this.ma&&(this.ma=this.ma.onmessage=null);this.ib&&(this.ib.terminate(),this.ib=null);this.Ca&&(this.Ca.c(),this.Ca=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}cd(){return h&&"cordova"===this.W}ob(){return h&&z.has(this.W)||navigator.standalone}async pd(f){if("playable-ad"===this.W){this.ha=self.c3_base64files;
this.Lb={};await this.Pe();for(let c=0,e=f.Ka.length;c<e;++c){var l=f.Ka[c].toLowerCase();this.Lb.hasOwnProperty(l)?f.Ka[c]={xg:!0,Ag:this.Lb[l]}:this.ha.hasOwnProperty(l)&&(f.Ka[c]=URL.createObjectURL(this.ha[l]))}}f.ug?this.V=f.ug:(l=location.origin,this.V=("null"===l?"file:///":l)+location.pathname,l=this.V.lastIndexOf("/"),-1!==l&&(this.V=this.V.substr(0,l+1)));if(f.Eg)for(const [c,e]of Object.entries(f.Eg))this.jb[c]=URL.createObjectURL(e);l=new MessageChannel;this.ma=l.port1;this.ma.onmessage=
c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.uf(c));this.Xa=new self.xe(this);await this.Xa.te();this.dd();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.gg();this.oa?await this.af(f,l.port2):await this.$e(f,l.port2)}nc(f){return this.jb.hasOwnProperty(f)?this.jb[f]:f.endsWith("/workermain.js")&&this.jb.hasOwnProperty("workermain.js")?
this.jb["workermain.js"]:"playable-ad"===this.W&&this.ha.hasOwnProperty(f.toLowerCase())?URL.createObjectURL(this.ha[f.toLowerCase()]):f}async Xb(f,l,c){if(f.startsWith("blob:"))return new Worker(f,c);if(this.cd()&&"file:"===location.protocol)return f=await this.Wb(this.Qc+f),new Worker(URL.createObjectURL(new Blob([f],{type:"application/javascript"})),c);f=new URL(f,l);if(location.origin!==f.origin){f=await fetch(f);if(!f.ok)throw Error("failed to fetch worker script");f=await f.blob();return new Worker(URL.createObjectURL(f),
c)}return new Worker(f,c)}dd(){if(this.ob()){const f=document.documentElement.style,l=document.body.style,c=window.innerWidth<window.innerHeight,e=c?window.screen.width:window.screen.height;l.height=f.height=(c?window.screen.height:window.screen.width)+"px";l.width=f.width=e+"px"}}od(f){return{baseUrl:this.V,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:u.cc(),projectData:f.Kg,previewImageBlobs:window.cr_previewImageBlobs||
this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:f.Td,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Jg,jobScheduler:this.Xa.re(),supportedAudioFormats:d,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Qc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Qc+"opus.wasm.wasm",isiOSCordova:this.cd(),isiOSWebView:this.ob(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async af(f,l){var c=this.nc(f.Dg);this.ib=await this.Xb(c,this.V,
{name:"Runtime"});this.I=document.createElement("canvas");this.I.style.display="none";c=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;this.ib.postMessage(Object.assign(this.od(f),{type:"init-runtime",isInWorker:!0,messagePort:l,canvas:c,workerDependencyScripts:f.Vc||[],engineScripts:f.Ka,projectScripts:window.Ig,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[l,c,...this.Xa.se()]);this.Gb=w.map(e=>new e(this));this.nd();self.c3_callFunction=(e,k)=>
this.Ha.bf(e,k);"preview"===this.W&&(self.goToLastErrorScript=()=>this.dc("runtime","go-to-last-error-script"))}async $e(f,l){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;this.Gb=w.map(e=>new e(this));this.nd();const c=f.Ka.map(e=>"string"===typeof e?(new URL(e,this.V)).toString():e);Array.isArray(f.Vc)&&c.unshift(...f.Vc);await Promise.all(c.map(e=>a(e)));if(f.Ud&&0<f.Ud.length){const e=self.C3_ProjectScriptsStatus;try{if(await Promise.all(f.Ud.map(k=>
a(k[1]))),Object.values(e).some(k=>!k)){self.setTimeout(()=>this.wd(e),100);return}}catch(k){console.error("[Preview] Error loading project scripts: ",k);self.setTimeout(()=>this.wd(e),100);return}}"preview"===this.W&&"object"!==typeof self.Fg.Hg?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(f=Object.assign(this.od(f),
{isInWorker:!1,messagePort:l,canvas:this.I,runOnStartupFunctions:B}),this.Ca=self.C3_CreateRuntime(f),await self.C3_InitRuntime(this.Ca,f))}wd(f){f=`Failed to load project script '${Object.entries(f).filter(l=>!l[1]).map(l=>l[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+f);alert(f)}async hf(){const f=await this.Xa.md();return{outputPort:f,transferables:[f]}}Ze(){if(this.oa)throw Error("not available in worker mode");return this.Ca}dc(f,l,c,e,k){this.ma.postMessage({type:"event",
component:f,handler:l,dispatchOpts:e||null,data:c,responseId:null},this.Tc?void 0:k)}ed(f,l,c,e,k){const m=x++,p=new Promise((r,G)=>{v.set(m,{resolve:r,reject:G})});this.ma.postMessage({type:"event",component:f,handler:l,dispatchOpts:e||null,data:c,responseId:m},this.Tc?void 0:k);return p}["_OnMessageFromRuntime"](f){const l=f.type;if("event"===l)return this.nf(f);if("result"===l)this.Bf(f);else if("runtime-ready"===l)this.Cf();else if("alert"===l)alert(f.message);else throw Error(`unknown message '${l}'`);
}nf(f){const l=f.component,c=f.handler,e=f.data,k=f.responseId;if(f=A.get(l))if(f=f.get(c)){var m=null;try{m=f(e)}catch(p){console.error(`Exception in '${l}' handler '${c}':`,p);null!==k&&this.zb(k,!1,""+p);return}if(null===k)return m;m&&m.then?m.then(p=>this.zb(k,!0,p)).catch(p=>{console.error(`Rejection from '${l}' handler '${c}':`,p);this.zb(k,!1,""+p)}):this.zb(k,!0,m)}else console.warn(`[DOM] No handler '${c}' for component '${l}'`);else console.warn(`[DOM] No event handlers for component '${l}'`)}zb(f,
l,c){let e;c&&c.transferables&&(e=c.transferables);this.ma.postMessage({type:"result",responseId:f,isOk:l,result:c},e)}Bf(f){const l=f.responseId,c=f.isOk;f=f.result;const e=v.get(l);c?e.resolve(f):e.reject(f);v.delete(l)}B(f,l,c){let e=A.get(f);e||(e=new Map,A.set(f,e));if(e.has(l))throw Error(`[DOM] Component '${f}' already has handler '${l}'`);e.set(l,c)}static Ub(f){if(w.includes(f))throw Error("DOM handler already added");w.push(f)}nd(){for(const f of this.Gb)if("runtime"===f.Qa){this.Ha=f;return}throw Error("cannot find runtime DOM handler");
}uf(f){this.dc("debugger","message",f)}Cf(){for(const f of this.Gb)f.Wc()}static cc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ke(f){this.Fa.push(f);this.yc()}Nf(f){f=this.Fa.indexOf(f);if(-1===f)throw Error("invalid callback");this.Fa.splice(f,1);this.Fa.length||this.kc()}yc(){-1===this.Ga&&this.Fa.length&&(this.Ga=requestAnimationFrame(this.sg))}kc(){-1!==this.Ga&&(cancelAnimationFrame(this.Ga),this.Ga=-1)}yf(){this.Ga=-1;for(const f of this.Fa)f();
this.yc()}ra(f){this.Ha.ra(f)}xa(f){this.Ha.xa(f)}xc(){this.Ha.xc()}sb(f){this.Ha.sb(f)}ve(){return!!d["audio/webm; codecs=opus"]}async lg(f){f=await this.ed("runtime","opus-decode",{arrayBuffer:f},null,[f]);return new Float32Array(f)}ue(f){return/^(?:[a-z]+:)?\/\//.test(f)||"data:"===f.substr(0,5)||"blob:"===f.substr(0,5)}we(f){return!this.ue(f)}async gf(f){const l=f.filename;switch(f.as){case "text":return await this.ke(l);case "buffer":return await this.Wb(l);default:throw Error("unsupported type");
}}Zc(f){const l=window.cordova.file.applicationDirectory+"www/"+f.toLowerCase();return new Promise((c,e)=>{window.resolveLocalFileSystemURL(l,k=>{k.file(c,e)},e)})}async ke(f){f=await this.Zc(f);return await g(f)}lc(){if(q.length&&!(8<=t)){t++;var f=q.shift();this.Qe(f.filename,f.Bg,f.wg)}}Wb(f){return new Promise((l,c)=>{q.push({filename:f,Bg:e=>{t--;this.lc();l(e)},wg:e=>{t--;this.lc();c(e)}});this.lc()})}async Qe(f,l,c){try{const e=await this.Zc(f),k=await n(e);l(k)}catch(e){c(e)}}async Pe(){const f=
[];for(const [l,c]of Object.entries(this.ha))f.push(this.Oe(l,c));await Promise.all(f)}async Oe(f,l){if("object"===typeof l)this.ha[f]=new Blob([l.str],{type:l.type}),this.Lb[f]=l.str;else{let c=await this.Xe(l);c||(c=this.Se(l));this.ha[f]=c}}async Xe(f){try{return await (await fetch(f)).blob()}catch(l){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
l),null}}Se(f){f=this.Hf(f);return this.Ne(f.data,f.yg)}Hf(f){var l=f.indexOf(",");if(0>l)throw new URIError("expected comma in data: uri");var c=f.substring(l+1);l=f.substring(5,l).split(";");f=l[0]||"";const e=l[2];c="base64"===l[1]||"base64"===e?atob(c):decodeURIComponent(c);return{yg:f,data:c}}Ne(f,l){var c=f.length;let e=c>>2,k=new Uint8Array(c),m=new Uint32Array(k.buffer,0,e),p,r;for(r=p=0;p<e;++p)m[p]=f.charCodeAt(r++)|f.charCodeAt(r++)<<8|f.charCodeAt(r++)<<16|f.charCodeAt(r++)<<24;for(c&=
3;c--;)k[r]=f.charCodeAt(r),++r;return new Blob([k],{type:l})}gg(){let f=null;const l=new Promise(k=>f=k),c=new ArrayBuffer(1),e=new MessageChannel;e.port2.onmessage=k=>{k.data&&k.data.arrayBuffer||(this.Tc=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));f()};e.port1.postMessage({arrayBuffer:c},[c]);return l}}}"use strict";
{const h=self.qb;function a(c){return c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(c){return new Promise((e,k)=>{const m=document.createElement("link");m.onload=()=>e(m);m.onerror=p=>k(p);m.rel=
"stylesheet";m.href=c;document.head.appendChild(m)})}function t(c){return new Promise((e,k)=>{const m=new Image;m.onload=()=>e(m);m.onerror=p=>k(p);m.src=c})}async function w(c){c=URL.createObjectURL(c);try{return await t(c)}finally{URL.revokeObjectURL(c)}}function A(c){return new Promise((e,k)=>{let m=new FileReader;m.onload=p=>e(p.target.result);m.onerror=p=>k(p);m.readAsText(c)})}async function v(c,e,k){if(!/firefox/i.test(navigator.userAgent))return await w(c);var m=await A(c);m=(new DOMParser).parseFromString(m,
"image/svg+xml");const p=m.documentElement;if(p.hasAttribute("width")&&p.hasAttribute("height")){const r=p.getAttribute("width"),G=p.getAttribute("height");if(!r.includes("%")&&!G.includes("%"))return await w(c)}p.setAttribute("width",e+"px");p.setAttribute("height",k+"px");m=(new XMLSerializer).serializeToString(m);c=new Blob([m],{type:"image/svg+xml"});return await w(c)}function x(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const B=new Set(["canvas",
"body","html"]);function z(c){B.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function u(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}self.C3_GetSvgImageSize=async function(c){c=await w(c);if(0<c.width&&0<c.height)return[c.width,c.height];{c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const e=c.getBoundingClientRect();document.body.removeChild(c);return[e.width,e.height]}};self.C3_RasterSvgImageBlob=async function(c,
e,k,m,p){c=await v(c,e,k);const r=document.createElement("canvas");r.width=m;r.height=p;r.getContext("2d").drawImage(c,0,0,e,k);return r};let f=!1;document.addEventListener("pause",()=>f=!0);document.addEventListener("resume",()=>f=!1);function l(){try{return window.parent&&window.parent.document.hasFocus()}catch(c){return!1}}h.Ub(class extends self.kb{constructor(c){super(c,"runtime");this.Gd=!0;this.Ia=-1;this.Rc="any";this.xd=this.yd=!1;this.Kc=this.fb=this.ta=null;c.B("canvas","update-size",m=>
this.Ff(m));c.B("runtime","invoke-download",m=>this.sf(m));c.B("runtime","raster-svg-image",m=>this.zf(m));c.B("runtime","get-svg-image-size",m=>this.qf(m));c.B("runtime","set-target-orientation",m=>this.Df(m));c.B("runtime","register-sw",()=>this.Af());c.B("runtime","post-to-debugger",m=>this.sd(m));c.B("runtime","go-to-script",m=>this.sd(m));c.B("runtime","before-start-ticking",()=>this.ff());c.B("runtime","debug-highlight",m=>this.jf(m));c.B("runtime","enable-device-orientation",()=>this.Me());
c.B("runtime","enable-device-motion",()=>this.Le());c.B("runtime","add-stylesheet",m=>this.df(m));c.B("runtime","alert",m=>this.ef(m));c.B("runtime","hide-cordova-splash",()=>this.rf());const e=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",m=>{const p=m.target;e.has(p.tagName.toLowerCase())||x(p)||m.preventDefault()});const k=c.I;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",z);k.addEventListener("selectstart",z);k.addEventListener("gesturehold",
z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),k.addEventListener("pointerdown",z)):k.addEventListener("touchstart",z);this.bb=0;window.addEventListener("mousedown",m=>{1===m.button&&m.preventDefault()});window.addEventListener("mousewheel",u,{passive:!1});window.addEventListener("wheel",u,{passive:!1});window.addEventListener("resize",()=>this.Gf());c.ob()&&window.addEventListener("focusout",()=>{{const r=
document.activeElement;if(r){var m=r.tagName.toLowerCase();var p=new Set("email number password search tel text url".split(" "));m="textarea"===m?!0:"input"===m?p.has(r.type.toLowerCase()||"text"):x(r)}else m=!1}m||(document.scrollingElement.scrollTop=0)});this.Da=new Set;this.Mb=new WeakSet;this.la=!1}ff(){"cordova"===this.A.W?(document.addEventListener("pause",()=>this.wc(!0)),document.addEventListener("resume",()=>this.wc(!1))):document.addEventListener("visibilitychange",()=>this.wc(document.hidden));
return{isSuspended:!(!document.hidden&&!f)}}Wc(){window.addEventListener("focus",()=>this.Ab("window-focus"));window.addEventListener("blur",()=>{this.Ab("window-blur",{parentHasFocus:l()});this.bb=0});window.addEventListener("fullscreenchange",()=>this.sc());window.addEventListener("webkitfullscreenchange",()=>this.sc());window.addEventListener("mozfullscreenchange",()=>this.sc());window.addEventListener("fullscreenerror",e=>this.tc(e));window.addEventListener("webkitfullscreenerror",e=>this.tc(e));
window.addEventListener("mozfullscreenerror",e=>this.tc(e));window.addEventListener("keydown",e=>this.rd("keydown",e));window.addEventListener("keyup",e=>this.rd("keyup",e));window.addEventListener("dblclick",e=>this.uc("dblclick",e,d));window.addEventListener("wheel",e=>this.wf(e));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",e=>{this.oc(e);this.Oa("pointerdown",e)}),this.A.oa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.fb=new self.Be(()=>this.Ve(),
5),this.fb.Bd=!0,window.addEventListener("pointerrawupdate",e=>this.xf(e))):window.addEventListener("pointermove",e=>this.Oa("pointermove",e)),window.addEventListener("pointerup",e=>this.Oa("pointerup",e)),window.addEventListener("pointercancel",e=>this.Oa("pointercancel",e))):(window.addEventListener("mousedown",e=>{this.oc(e);this.vc("pointerdown",e)}),window.addEventListener("mousemove",e=>this.vc("pointermove",e)),window.addEventListener("mouseup",e=>this.vc("pointerup",e)),window.addEventListener("touchstart",
e=>{this.oc(e);this.yb("pointerdown",e)}),window.addEventListener("touchmove",e=>this.yb("pointermove",e)),window.addEventListener("touchend",e=>this.yb("pointerup",e)),window.addEventListener("touchcancel",e=>this.yb("pointercancel",e)));const c=()=>this.xc();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0)}Ab(c,e){y(this,c,e||null,n)}wb(){return Math.max(window.innerWidth,
1)}vb(){return Math.max(window.innerHeight,1)}Gf(){const c=this.wb(),e=this.vb();this.Ab("window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio});this.A.ob()&&(-1!==this.Ia&&clearTimeout(this.Ia),this.td(c,e,0))}Of(c,e,k){-1!==this.Ia&&clearTimeout(this.Ia);this.Ia=setTimeout(()=>this.td(c,e,k),48)}td(c,e,k){const m=this.wb(),p=this.vb();this.Ia=-1;m!=c||p!=e?this.Ab("window-resize",{innerWidth:m,innerHeight:p,devicePixelRatio:window.devicePixelRatio}):10>k&&this.Of(m,
p,k+1)}Df(c){this.Rc=c.targetOrientation}hg(){const c=this.Rc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(e=>console.warn("[Construct 3] Failed to lock orientation: ",e));else try{let e=!1;screen.lockOrientation?e=screen.lockOrientation(c):screen.webkitLockOrientation?e=screen.webkitLockOrientation(c):screen.mozLockOrientation?e=screen.mozLockOrientation(c):screen.msLockOrientation&&(e=screen.msLockOrientation(c));e||console.warn("[Construct 3] Failed to lock orientation")}catch(e){console.warn("[Construct 3] Failed to lock orientation: ",
e)}}sc(){const c=h.cc();c&&"any"!==this.Rc&&this.hg();y(this,"fullscreenchange",{isFullscreen:c,innerWidth:this.wb(),innerHeight:this.vb()})}tc(c){console.warn("[Construct 3] Fullscreen request failed: ",c);y(this,"fullscreenerror",{isFullscreen:h.cc(),innerWidth:this.wb(),innerHeight:this.vb()})}wc(c){c?this.A.kc():this.A.yc();y(this,"visibilitychange",{hidden:c})}rd(c,e){"Backspace"===e.key&&z(e);const k=b.get(e.code)||e.code;C(this,c,{code:k,key:e.key,which:e.which,repeat:e.repeat,altKey:e.altKey,
ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,timeStamp:e.timeStamp},d)}wf(c){y(this,"wheel",{clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,deltaX:c.deltaX,deltaY:c.deltaY,deltaZ:c.deltaZ,deltaMode:c.deltaMode,timeStamp:c.timeStamp},d)}uc(c,e,k){a(e)||C(this,c,{button:e.button,buttons:e.buttons,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,timeStamp:e.timeStamp},k)}vc(c,e){if(!a(e)){var k=this.bb;"pointerdown"===c&&0!==k?c="pointermove":"pointerup"===
c&&0!==e.buttons&&(c="pointermove");C(this,c,{pointerId:1,pointerType:"mouse",button:e.button,buttons:e.buttons,lastButtons:k,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:e.timeStamp},d);this.bb=e.buttons;this.uc(e.type,e,g)}}Oa(c,e){if(this.fb&&"pointermove"!==c){var k=this.fb;k.Va||(H(k),k.Jb=Date.now())}k=0;"mouse"===e.pointerType&&(k=this.bb);C(this,c,{pointerId:e.pointerId,pointerType:e.pointerType,
button:e.button,buttons:e.buttons,lastButtons:k,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:e.width||0,height:e.height||0,pressure:e.pressure||0,tangentialPressure:e.tangentialPressure||0,tiltX:e.tiltX||0,tiltY:e.tiltY||0,twist:e.twist||0,timeStamp:e.timeStamp},d);"mouse"===e.pointerType&&(k="mousemove","pointerdown"===c?k="mousedown":"pointerup"===c&&(k="pointerup"),this.uc(k,e,g),this.bb=e.buttons)}xf(c){this.Kc=c;c=this.fb;if(-1===c.Ja){var e=Date.now(),k=e-c.Jb,m=c.ng;
k>=m&&c.Bd?(c.Jb=e,c.Va=!0,c.Bc(),c.Va=!1):c.Ja=self.setTimeout(c.Sd,Math.max(m-k,4))}}Ve(){this.Oa("pointermove",this.Kc);this.Kc=null}yb(c,e){for(let k=0,m=e.changedTouches.length;k<m;++k){const p=e.changedTouches[k];C(this,c,{pointerId:p.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:p.clientX,clientY:p.clientY,pageX:p.pageX,pageY:p.pageY,width:2*(p.radiusX||p.webkitRadiusX||0),height:2*(p.radiusY||p.webkitRadiusY||0),pressure:p.force||p.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:p.rotationAngle||0,timeStamp:e.timeStamp},d)}}oc(c){window!==window.top&&window.focus();this.qd(c.target)&&document.activeElement&&!this.qd(document.activeElement)&&document.activeElement.blur()}qd(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}Me(){this.yd||(this.yd=!0,window.addEventListener("deviceorientation",c=>this.lf(c)),window.addEventListener("deviceorientationabsolute",c=>this.mf(c)))}Le(){this.xd||(this.xd=!0,window.addEventListener("devicemotion",
c=>this.kf(c)))}lf(c){y(this,"deviceorientation",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp,webkitCompassHeading:c.webkitCompassHeading,webkitCompassAccuracy:c.webkitCompassAccuracy},d)}mf(c){y(this,"deviceorientationabsolute",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp},d)}kf(c){let e=null;var k=c.acceleration;k&&(e={x:k.x||0,y:k.y||0,z:k.z||0});k=null;var m=c.accelerationIncludingGravity;m&&(k={x:m.x||
0,y:m.y||0,z:m.z||0});m=null;const p=c.rotationRate;p&&(m={alpha:p.alpha||0,beta:p.beta||0,gamma:p.gamma||0});y(this,"devicemotion",{acceleration:e,accelerationIncludingGravity:k,rotationRate:m,interval:c.interval,timeStamp:c.timeStamp},d)}Ff(c){const e=this.A,k=e.I;k.style.width=c.styleWidth+"px";k.style.height=c.styleHeight+"px";k.style.marginLeft=c.marginLeft+"px";k.style.marginTop=c.marginTop+"px";e.dd();this.Gd&&(k.style.display="",this.Gd=!1)}sf(c){const e=c.url;c=c.filename;const k=document.createElement("a"),
m=document.body;k.textContent=c;k.href=e;k.download=c;m.appendChild(k);k.click();m.removeChild(k)}async zf(c){var e=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);e=e?await createImageBitmap(c,e):await createImageBitmap(c);return{imageBitmap:e,transferables:[e]}}async qf(c){return await self.C3_GetSvgImageSize(c.blob)}async df(c){await q(c.url)}xc(){var c=[...this.Da];this.Da.clear();if(!this.la)for(const e of c)(c=e.play())&&
c.catch(()=>{this.Mb.has(e)||this.Da.add(e)})}ra(c){if("function"!==typeof c.play)throw Error("missing play function");this.Mb.delete(c);let e;try{e=c.play()}catch(k){this.Da.add(c);return}e&&e.catch(()=>{this.Mb.has(c)||this.Da.add(c)})}xa(c){this.Da.delete(c);this.Mb.add(c)}sb(c){this.la=!!c}rf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}jf(c){if(c.show){this.ta||(this.ta=document.createElement("div"),this.ta.id="inspectOutline",document.body.appendChild(this.ta));
var e=this.ta;e.style.display="";e.style.left=c.left-1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.ta&&(this.ta.style.display="none")}Af(){window.C3_RegisterSW&&window.C3_RegisterSW()}sd(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}bf(c,e){return this.A.ed(this.Qa,"js-invoke-function",{name:c,params:e},void 0,void 0)}ef(c){alert(c.message)}})}"use strict";
{const h=document.currentScript.src;self.xe=class{constructor(a){this.Qb=a;this.V=h?h.substr(0,h.lastIndexOf("/")+1):a.V;this.pg=Math.min(navigator.hardwareConcurrency||2,16);this.Dc=null;this.Hd=[];this.Oc=this.Hc=null}async te(){if(this.mg)throw Error("already initialised");this.mg=!0;var a=this.Qb.nc("dispatchworker.js");this.Dc=await this.Qb.Xb(a,this.V,{name:"DispatchWorker"});a=new MessageChannel;this.Hc=a.port1;this.Dc.postMessage({type:"_init","in-port":a.port2},[a.port2]);this.Oc=await this.md()}async md(){const a=
this.Hd.length;var b=this.Qb.nc("jobworker.js");b=await this.Qb.Xb(b,this.V,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;this.Dc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);this.Hd.push(b);return g.port1}re(){return{inputPort:this.Hc,outputPort:this.Oc,maxNumWorkers:this.pg}}se(){return[this.Hc,this.Oc]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.qb({Cg:!0,Dg:"workermain.js",Ka:["scripts/c3runtime.js"],zg:"scripts/",Vc:["box2d.wasm.js"],Td:"html5"}));"use strict";self.qb.Ub(class extends self.kb{constructor(h){super(h,"mouse");D(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
{const h=180/Math.PI;self.da=class extends self.kb{constructor(a){super(a,"audio");this.Fb=this.f=null;this.Hb=this.Gc=!1;this.na=()=>this.ig();this.aa=[];this.C=[];this.ga=null;this.Id="";this.Jd=-1;this.eb=new Map;this.Lc=1;this.la=!1;this.Sc=0;this.Sb=1;this.Ec=0;this.Ld="HRTF";this.Cd="inverse";this.Md=600;this.Kd=1E4;this.Od=1;this.Ed=this.Pc=!1;this.tg=this.A.ve();this.ba=new Map;this.Aa=new Set;this.Ic=!1;this.Mc="";this.ua=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.vf(b,d);this.Eb=null;
self.C3Audio_GetOutputStream=()=>this.pf();self.C3Audio_DOMInterface=this;E(this,[["create-audio-context",b=>this.Re(b)],["play",b=>this.If(b)],["stop",b=>this.eg(b)],["stop-all",()=>this.fg()],["set-paused",b=>this.Yf(b)],["set-volume",b=>this.cg(b)],["fade-volume",b=>this.We(b)],["set-master-volume",b=>this.Wf(b)],["set-muted",b=>this.Xf(b)],["set-silent",b=>this.$f(b)],["set-looping",b=>this.Vf(b)],["set-playback-rate",b=>this.Zf(b)],["seek",b=>this.Pf(b)],["preload",b=>this.Jf(b)],["unload",b=>
this.jg(b)],["unload-all",()=>this.kg()],["set-suspended",b=>this.ag(b)],["add-effect",b=>this.kd(b)],["set-effect-param",b=>this.Sf(b)],["remove-effects",b=>this.Lf(b)],["tick",b=>this.Ef(b)],["load-state",b=>this.tf(b)]])}async Re(a){a.isiOSCordova&&(this.Pc=!0);this.Sc=a.timeScaleMode;this.Ld=["equalpower","HRTF","soundfield"][a.panningModel];this.Cd=["linear","inverse","exponential"][a.distanceModel];this.Md=a.refDistance;this.Kd=a.maxDistance;this.Od=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.ld();this.f.onstatechange=()=>{"running"!==this.f.state&&this.ld()};this.Fb=this.f.createGain();this.Fb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.Yb();try{await Promise.all(a.preloadList.map(d=>
this.ub(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}ld(){this.Hb||(this.Gc=!1,window.addEventListener("pointerup",this.na,!0),window.addEventListener("touchend",this.na,!0),window.addEventListener("click",this.na,!0),window.addEventListener("keydown",this.na,!0),this.Hb=!0)}Te(){this.Hb&&(this.Gc=!0,window.removeEventListener("pointerup",this.na,!0),window.removeEventListener("touchend",this.na,!0),window.removeEventListener("click",
this.na,!0),window.removeEventListener("keydown",this.na,!0),this.Hb=!1)}ig(){if(!this.Gc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.Te()}}U(){return this.f}Yb(){return this.f.currentTime}pa(){return this.Fb}ad(a){return(a=this.ba.get(a.toLowerCase()))?a[0].N():this.pa()}Vd(a,b){a=a.toLowerCase();let d=this.ba.get(a);d||(d=[],this.ba.set(a,d));b.Uf(d.length);
b.bg(a);d.push(b);this.vd(a)}vd(a){let b=this.pa();const d=this.ba.get(a);if(d&&d.length){b=d[0].N();for(let g=0,n=d.length;g<n;++g){const q=d[g];g+1===n?q.P(this.pa()):q.P(d[g+1].N())}}for(const g of this.ja(a))g.Ce(b);this.ua&&this.Mc===a&&(this.ua.disconnect(),this.ua.connect(b))}mb(){return this.Lc}nb(){return this.la}Tf(){this.Ed=!0}me(a,b){return b?this.A.lg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):new Promise((d,g)=>{this.f.decodeAudioData(a,
d,g)})}ra(a){this.A.ra(a)}xa(a){this.A.xa(a)}fd(a){let b=0;for(let d=0,g=this.C.length;d<g;++d){const n=this.C[d];this.C[b]=n;n.J===a?n.c():++b}this.C.length=b}De(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.qa()?g.c():++a}this.aa.length=a}*ja(a){if(a)for(const b of this.C)self.da.ne(b.Z,a)&&(yield b);else this.ga&&!this.ga.R()&&(yield this.ga)}async ub(a,b,d,g,n){for(const q of this.aa)if(q.Ma()===b)return await J(q),q;if(n)return null;g&&(this.Pc||this.Ed)&&
this.De();n="audio/webm; codecs=opus"===d&&!this.tg;g&&n&&this.Tf();a=!g||this.Pc||n?new self.ie(this,a,b,d,g,n):new self.ge(this,a,b,d,g);this.aa.push(a);await J(a);return a}async mc(a,b,d,g,n){for(const q of this.C)if(q.Ma()===b&&(q.Vb()||n))return q.Fe(g),q;a=await this.ub(a,b,d,n);g="html5"===a.zc?new self.he(a.i,a,g):new self.je(a.i,a,g);this.C.push(g);return g}Je(a){let b=this.eb.get(a);if(!b){let d=null;b={Uc:0,promise:new Promise(g=>d=g),resolve:d};this.eb.set(a,b)}b.Uc++}Mf(a){const b=this.eb.get(a);
if(!b)throw Error("expected pending tag");b.Uc--;0===b.Uc&&(b.resolve(),this.eb.delete(a))}jc(a){a||(a=this.Id);return(a=this.eb.get(a))?a.promise:Promise.resolve()}xb(){if(0<this.Aa.size)F(this);else for(const a of this.C)if(a.bd()){F(this);break}}ya(){for(var a of this.Aa)a.ya();a=this.Yb();for(var b of this.C)b.ya(a);b=this.C.filter(d=>d.bd()).map(d=>d.La());y(this,"state",{tickCount:this.Jd,audioInstances:b,analysers:[...this.Aa].map(d=>d.pe())});0===b.length&&0===this.Aa.size&&this.Ib&&(this.A.Nf(this.Rd),
this.Ib=!1)}ec(a,b,d){y(this,"trigger",{type:a,tag:b,aiid:d})}async If(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,q=a.tag,t=a.isLooping,w=a.vol,A=a.pos,v=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Id=q;this.Je(q);try{this.ga=await this.mc(b,d,g,q,n),v?(this.ga.rb(!0),this.ga.Ee(v.x,v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&
this.ga.Ge(v.uid)):this.ga.rb(!1),this.ga.Play(t,w,A,x)}catch(B){console.error("[Construct 3] Audio: error starting playback: ",B);return}finally{this.Mf(q)}F(this)}eg(a){a=a.tag;for(const b of this.ja(a))b.ka()}fg(){for(const a of this.C)a.ka()}Yf(a){const b=a.tag;a=a.paused;for(const d of this.ja(b))a?d.Na():d.pb();this.xb()}cg(a){const b=a.tag;a=a.vol;for(const d of this.ja(b))d.tb(a)}async We(a){const b=a.tag,d=a.vol,g=a.duration;a=a.stopOnEnd;await this.jc(b);for(const n of this.ja(b))n.oe(d,
g,a);this.xb()}Wf(a){this.Lc=a.vol;for(const b of this.C)b.Cb()}Xf(a){const b=a.tag;a=a.isMuted;for(const d of this.ja(b))d.gd(a)}$f(a){this.la=a.isSilent;this.A.sb(this.la);for(const b of this.C)b.Bb()}Vf(a){const b=a.tag;a=a.isLooping;for(const d of this.ja(b))d.hc(a)}async Zf(a){const b=a.tag;a=a.rate;await this.jc(b);for(const d of this.ja(b))d.jd(a)}async Pf(a){const b=a.tag;a=a.pos;await this.jc(b);for(const d of this.ja(b))d.fc(a)}async Jf(a){const b=a.originalUrl,d=a.url,g=a.type;a=a.isMusic;
try{await this.mc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async jg(a){if(a=await this.ub("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}kg(){for(const a of this.aa)a.c();this.aa.length=0}ag(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.ic(a);a&&this.f.suspend&&this.f.suspend()}Ef(a){this.Sb=a.timeScale;this.Ec=a.gameTime;this.Jd=a.tickCount;if(0!==this.Sc)for(var b of this.C)b.za();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.C)g.fa===a&&g.hd(d.x,d.y,d.angle)}}async kd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.ae(this,...g);else if("delay"===b)g=new self.Zd(this,...g);else if("convolution"===b){b=null;try{b=await this.ub(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",n);return}g=new self.Yd(this,b.$,...g);g.Qf(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)g=new self.be(this,...g);else if("phaser"===b)g=new self.de(this,...g);else if("gain"===b)g=new self.ce(this,...g);else if("tremolo"===b)g=new self.fe(this,...g);else if("ringmod"===b)g=new self.ee(this,...g);else if("distortion"===b)g=new self.$d(this,...g);else if("compressor"===b)g=new self.Xd(this,...g);else if("analyser"===b)g=new self.Wd(this,...g);else throw Error("invalid effect type");this.Vd(d,g);this.ud()}Sf(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,
q=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,q),this.ud())}Lf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.vd(a)}}Ie(a){this.Aa.add(a);this.xb()}Kf(a){this.Aa.delete(a)}ud(){this.Ic||(this.Ic=!0,Promise.resolve().then(()=>this.Ue()))}Ue(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.La());y(this,"fxstate",{fxstate:a});this.Ic=!1}async tf(a){const b=a.saveLoadMode;if(3!==b)for(var d of this.C)d.qa()&&1===
b||(d.qa()||2!==b)&&d.ka();for(const g of this.ba.values())for(const n of g)n.c();this.ba.clear();this.Sb=a.timeScale;this.Ec=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.la=a.isSilent;this.A.sb(this.la);this.Lc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.kd(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.cf(g,b)));this.xb()}async cf(a,b){if(3!==b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,
q=a.isMusic,t=a.tag,w=a.isLooping,A=a.volume,v=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.mc(d,g,n,t,q)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Ae(a.pan);b.Play(w,A,v,0);a.isPlaying||b.Na();b.qc(a)}}}vf(a,b){this.ua&&this.ua.disconnect();this.Mc=b.toLowerCase();this.ua=this.f.createMediaStreamSource(a);this.ua.connect(this.ad(this.Mc))}pf(){this.Eb||(this.Eb=this.f.createMediaStreamDestination(),this.Fb.connect(this.Eb));return this.Eb.stream}static ne(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static He(a){return a*h}static le(a){return Math.pow(10,a/20)}static $c(a){return Math.max(Math.min(self.da.le(a),1),0)}static ze(a){return Math.log(a)/Math.log(10)*20}static ye(a){return self.da.ze(Math.max(Math.min(a,1),0))}static vg(a,b){return 1-Math.exp(-b*a)}};self.qb.Ub(self.da)}"use strict";function J(h){h.Kb||(h.Kb=h.pc());return h.Kb}
self.Xc=class{constructor(h,a,b,d,g){this.i=h;this.rg=a;this.va=b;this.O=d;this.og=g;this.zc="";this.Kb=null}c(){this.Kb=this.i=null}pc(){}U(){return this.i.U()}$b(){return this.rg}Ma(){return this.va}Zb(){return this.O}qa(){return this.og}ea(){}};"use strict";
self.ge=class extends self.Xc{constructor(h,a,b,d,g){super(h,a,b,d,g);this.zc="html5";this.H=new Audio;this.H.crossOrigin="anonymous";this.H.autoplay=!1;this.H.preload="auto";this.Ya=this.Za=null;this.H.addEventListener("canplaythrough",()=>!0);this.cb=this.U().createGain();this.ab=null;this.H.addEventListener("canplay",()=>{this.Za&&(this.Za(),this.Ya=this.Za=null);!this.ab&&this.H&&(this.ab=this.U().createMediaElementSource(this.H),this.ab.connect(this.cb))});this.onended=null;this.H.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.H.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.va}' error: `,n);this.Ya&&(this.Ya(n),this.Ya=this.Za=null)})}c(){this.i.fd(this);this.cb.disconnect();this.cb=null;this.ab.disconnect();this.ab=null;this.H&&!this.H.paused&&this.H.pause();this.H=this.onended=null;super.c()}pc(){return new Promise((h,a)=>{this.Za=h;this.Ya=a;this.H.src=this.va})}M(){return this.H}ea(){return this.H.duration}};"use strict";
async function K(h){if(h.sa)return h.sa;var a=h.i.A;if("cordova"===a.W&&a.we(h.va)&&"file:"===location.protocol)h.sa=await a.Wb(h.va);else{a=await fetch(h.va);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);h.sa=await a.arrayBuffer()}}async function L(h){if(h.$)return h.$;h.$=await h.i.me(h.sa,h.qg);h.sa=null}
self.ie=class extends self.Xc{constructor(h,a,b,d,g,n){super(h,a,b,d,g);this.zc="webaudio";this.$=this.sa=null;this.qg=!!n}c(){this.i.fd(this);this.$=this.sa=null;super.c()}async pc(){try{await K(this),await L(this)}catch(h){console.error(`[Construct 3] Failed to load audio '${this.va}': `,h)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let h=0;self.Yc=class{constructor(a,b,d){this.i=a;this.J=b;this.Z=d;this.Db=h++;this.K=this.U().createGain();this.K.connect(this.pa());this.v=null;this.Wa=!1;this.F=!0;this.T=this.ia=this.D=!1;this.hb=1;this.Ba=!1;this.Y=1;a=this.i.Sc;this.Jc=1===a&&!this.qa()||2===a;this.Ta=this.fa=-1;this.Qd=!1}c(){this.J=this.i=null;this.v&&(this.v.disconnect(),this.v=null);this.K.disconnect();this.K=null}U(){return this.i.U()}pa(){return this.i.ad(this.Z)}mb(){return this.i.mb()}lb(){return this.Jc?this.i.Ec:
performance.now()/1E3}$b(){return this.J.$b()}Ma(){return this.J.Ma()}Zb(){return this.J.Zb()}qa(){return this.J.qa()}Fe(a){this.Z=a}R(){}Vb(){}IsPlaying(){return!this.F&&!this.D&&!this.R()}bd(){return!this.F&&!this.R()}wa(){}ea(){return this.J.ea()}Play(){}ka(){}Na(){}pb(){}tb(a){this.hb=a;this.K.gain.cancelScheduledValues(0);this.Ta=-1;this.K.gain.value=this.ac()}oe(a,b,d){if(!this.Ba){a*=this.mb();var g=this.K.gain;g.cancelScheduledValues(0);var n=this.i.Yb();b=n+b;g.setValueAtTime(g.value,n);
g.linearRampToValueAtTime(a,b);this.hb=a;this.Ta=b;this.Qd=d}}Cb(){this.tb(this.hb)}ya(a){-1!==this.Ta&&a>=this.Ta&&(this.Ta=-1,this.Qd&&this.ka(),this.i.ec("fade-ended",this.Z,this.Db))}ac(){const a=this.hb*this.mb();return isFinite(a)?a:0}gd(a){a=!!a;this.Ba!==a&&(this.Ba=a,this.Bb())}nb(){return this.i.nb()}Bb(){}hc(){}jd(a){this.Y!==a&&(this.Y=a,this.za())}za(){}fc(){}ic(){}rb(a){a=!!a;this.Wa!==a&&((this.Wa=a)?(this.v||(this.v=this.U().createPanner(),this.v.panningModel=this.i.Ld,this.v.distanceModel=
this.i.Cd,this.v.refDistance=this.i.Md,this.v.maxDistance=this.i.Kd,this.v.rolloffFactor=this.i.Od),this.K.disconnect(),this.K.connect(this.v),this.v.connect(this.pa())):(this.v.disconnect(),this.K.disconnect(),this.K.connect(this.pa())))}Ee(a,b,d,g,n,q){this.Wa&&(this.hd(a,b,d),a=self.da.He,this.v.coneInnerAngle=a(g),this.v.coneOuterAngle=a(n),this.v.coneOuterGain=q)}hd(a,b,d){this.Wa&&(this.v.setPosition(a,b,0),this.v.setOrientation(Math.cos(d),Math.sin(d),0))}Ge(a){this.fa=a}bc(){}Ce(a){const b=
this.v||this.K;b.disconnect();b.connect(a)}La(){return{aiid:this.Db,tag:this.Z,duration:this.ea(),volume:this.hb,isPlaying:this.IsPlaying(),playbackTime:this.wa(),playbackRate:this.Y,uid:this.fa,bufferOriginalUrl:this.$b(),bufferUrl:"",bufferType:this.Zb(),isMusic:this.qa(),isLooping:this.T,isMuted:this.Ba,resumePosition:this.bc(),pan:this.qe()}}qc(a){this.jd(a.playbackRate);this.gd(a.isMuted)}qe(){if(!this.v)return null;const a=this.v;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Ae(a){a?(this.rb(!0),a=this.v,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.rb(!1)}}}"use strict";
self.he=class extends self.Yc{constructor(h,a,b){super(h,a,b);this.J.cb.connect(this.K);this.J.onended=()=>this.rc()}c(){this.ka();this.J.cb.disconnect();super.c()}M(){return this.J.M()}rc(){this.F=!0;this.fa=-1;this.i.ec("ended",this.Z,this.Db)}R(){return this.M().ended}Vb(){return this.F?!0:this.R()}wa(h){let a=this.M().currentTime;h&&(a*=this.Y);this.T||(a=Math.min(a,this.ea()));return a}Play(h,a,b){const d=this.M();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==h&&(d.loop=h);this.tb(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.J.Ma()}' to position '${b}': `,g)}this.i.ra(d);this.D=this.F=!1;this.T=h;this.Y=1}ka(){const h=this.M();h.paused||h.pause();this.i.xa(h);this.F=!0;this.D=!1;this.fa=-1}Na(){if(!(this.D||this.F||this.R())){var h=this.M();h.paused||h.pause();this.i.xa(h);this.D=!0}}pb(){!this.D||this.F||this.R()||(this.i.ra(this.M()),this.D=!1)}Bb(){this.M().muted=this.Ba||this.nb()}hc(h){h=!!h;
this.T!==h&&(this.T=h,this.M().loop=h)}za(){let h=this.Y;this.Jc&&(h*=this.i.Sb);try{this.M().playbackRate=h}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${h}':`,a)}}fc(h){if(!this.F&&!this.R())try{this.M().currentTime=h}catch(a){console.warn(`[Construct 3] Error seeking audio to '${h}': `,a)}}bc(){return this.wa()}ic(h){h?this.IsPlaying()?(this.M().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.ra(this.M()),this.ia=!1)}};"use strict";
function M(h){h.j&&h.j.disconnect();h.j=null;h.Pa=null}
self.je=class extends self.Yc{constructor(h,a,b){super(h,a,b);this.j=null;this.Nb=d=>this.rc(d);this.Fc=!0;this.Pa=null;this.L=this.Rb=0;this.Nc=1}c(){this.ka();M(this);this.Nb=null;super.c()}rc(h){this.D||this.ia||h.target!==this.Pa||(this.F=this.Fc=!0,this.fa=-1,M(this),this.i.ec("ended",this.Z,this.Db))}R(){return!this.F&&this.j&&this.j.loop||this.D?!1:this.Fc}Vb(){return!this.j||this.F?!0:this.R()}wa(h){let a;a=this.D?this.L:this.lb()-this.Rb;h&&(a*=this.Y);this.T||(a=Math.min(a,this.ea()));return a}Play(h,
a,b,d){this.Nc=1;this.tb(a);M(this);this.j=this.U().createBufferSource();this.j.buffer=this.J.$;this.j.connect(this.K);this.Pa=this.j;this.j.onended=this.Nb;this.j.loop=h;this.j.start(d,b);this.D=this.F=this.Fc=!1;this.T=h;this.Y=1;this.Rb=this.lb()-b}ka(){if(this.j)try{this.j.stop(0)}catch(h){}this.F=!0;this.D=!1;this.fa=-1}Na(){this.D||this.F||this.R()||(this.L=this.wa(!0),this.T&&(this.L%=this.ea()),this.D=!0,this.j.stop(0))}pb(){!this.D||this.F||this.R()||(M(this),this.j=this.U().createBufferSource(),
this.j.buffer=this.J.$,this.j.connect(this.K),this.Pa=this.j,this.j.onended=this.Nb,this.j.loop=this.T,this.Cb(),this.za(),this.Rb=this.lb()-this.L/(this.Y||.001),this.j.start(0,this.L),this.D=!1)}ac(){return super.ac()*this.Nc}Bb(){this.Nc=this.Ba||this.nb()?0:1;this.Cb()}hc(h){h=!!h;this.T!==h&&(this.T=h,this.j&&(this.j.loop=h))}za(){let h=this.Y;this.Jc&&(h*=this.i.Sb);this.j&&(this.j.playbackRate.value=h)}fc(h){this.F||this.R()||(this.D?this.L=h:(this.Na(),this.L=h,this.pb()))}bc(){return this.L}ic(h){h?
this.IsPlaying()?(this.ia=!0,this.L=this.wa(!0),this.T&&(this.L%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(M(this),this.j=this.U().createBufferSource(),this.j.buffer=this.J.$,this.j.connect(this.K),this.Pa=this.j,this.j.onended=this.Nb,this.j.loop=this.T,this.Cb(),this.za(),this.Rb=this.lb()-this.L/(this.Y||.001),this.j.start(0,this.L),this.ia=!1)}qc(h){super.qc(h);this.L=h.resumePosition}};"use strict";
{class h{constructor(a){this.i=a;this.f=a.U();this.Fd=-1;this.O=this.Z="";this.g=null}c(){this.f=null}Uf(a){this.Fd=a}bg(a){this.Z=a}o(){return this.f.createGain()}N(){}P(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.f.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}La(){return{type:this.O,tag:this.Z,params:this.g}}}
self.ae=class extends h{constructor(a,b,d,g,n,q,t){super(a);this.O="filter";this.g=[b,d,g,n,q,t];this.l=this.o();this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=g;this.u.Q.value=n;this.u.gain.vlaue=q;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,g)}}};self.Zd=class extends h{constructor(a,b,d,g){super(a);this.O="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.$a=this.o();this.S=this.f.createDelay(b);this.S.delayTime.value=b;this.Sa=this.o();this.Sa.gain.value=d;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b);this.$a.connect(this.S);this.S.connect(this.Sa);this.Sa.connect(this.$a)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.$a.disconnect();this.S.disconnect();this.Sa.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,d,g){const n=self.da.$c;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.Sa.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.S.delayTime,b,d,g)}}};self.Yd=class extends h{constructor(a,b,d,g){super(a);this.O="convolution";this.g=[d,g];this.Ad=this.zd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.Ra=this.f.createConvolver();this.Ra.normalize=d;this.Ra.buffer=b;this.l.connect(this.Ra);this.l.connect(this.a);this.Ra.connect(this.b)}c(){this.l.disconnect();this.Ra.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}Qf(a,b){this.zd=a;this.Ad=b}La(){const a=
super.La();a.bufferOriginalUrl=this.zd;a.bufferUrl="";a.bufferType=this.Ad;return a}};self.be=class extends h{constructor(a,b,d,g,n,q){super(a);this.O="flanger";this.g=[b,d,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.Ua=this.o();this.Ua.gain.value=n;this.S=this.f.createDelay(b+d);this.S.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.G=this.o();this.G.gain.value=d;this.l.connect(this.S);this.l.connect(this.a);
this.S.connect(this.b);this.S.connect(this.Ua);this.Ua.connect(this.S);this.s.connect(this.G);this.G.connect(this.S.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.S.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();this.Ua.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.G.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.Ua.gain,b/100,d,g)}}};self.de=class extends h{constructor(a,b,d,g,n,q,t){super(a);this.O="phaser";this.g=[b,d,g,n,q,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=q;this.G=this.o();this.G.gain.value=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.G);this.G.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.G.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,g)}}};self.ce=class extends h{constructor(a,b){super(a);this.O="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}X(a,b,d,g){const n=self.da.$c;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.fe=class extends h{constructor(a,b,d){super(a);this.O="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.G=this.o();this.G.gain.value=d/2;this.s.connect(this.G);this.G.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.G.disconnect();this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,d,g);this.m(this.G.gain.value,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ee=class extends h{constructor(a,b,d){super(a);this.O="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.gb=this.o();
this.gb.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.gb.gain);this.s.start(0);this.l.connect(this.gb);this.l.connect(this.a);this.gb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.gb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,d,g);this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.$d=class extends h{constructor(a,b,d,g,n,q){super(a);this.O="distortion";this.g=[b,d,g,n,q];this.l=this.o();this.Pb=this.o();this.Ob=this.o();this.Rf(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.Tb=this.f.createWaveShaper();this.Cc=new Float32Array(65536);this.Ye(b,d);this.Tb.curve=this.Cc;this.l.connect(this.Pb);this.l.connect(this.a);this.Pb.connect(this.Tb);
this.Tb.connect(this.Ob);this.Ob.connect(this.b)}c(){this.l.disconnect();this.Pb.disconnect();this.Tb.disconnect();this.Ob.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Rf(a,b){.01>a&&(a=.01);this.Pb.gain.value=a;this.Ob.gain.value=Math.pow(1/a,.6)*b}Ye(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.dg(g,a,b);this.Cc[32768+d]=g;this.Cc[32768-d-1]=-g}}dg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.vg(g-b,1/d))*(0>a?-1:1)}P(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.Xd=class extends h{constructor(a,b,d,g,n,q){super(a);this.O="compressor";this.g=[b,d,g,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}X(){}};
self.Wd=class extends h{constructor(a,b,d){super(a);this.O="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Dd=new Float32Array(this.h.frequencyBinCount);this.Pd=new Uint8Array(b);this.Nd=this.Ea=0;this.i.Ie(this)}c(){this.i.Kf(this);this.h.disconnect();super.c()}ya(){this.h.getFloatFrequencyData(this.Dd);this.h.getByteTimeDomainData(this.Pd);const a=this.h.fftSize;let b=this.Ea=0;for(var d=0;d<a;++d){let g=(this.Pd[d]-128)/128;0>g&&(g=-g);
this.Ea<g&&(this.Ea=g);b+=g*g}d=self.da.ye;this.Ea=d(this.Ea);this.Nd=d(Math.sqrt(b/a))}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}X(){}pe(){return{tag:this.Z,index:this.Fd,peak:this.Ea,rms:this.Nd,binCount:this.h.frequencyBinCount,freqBins:this.Dd}}}};